{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"viewDidAppear(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CleanUI@objc(cs)CUScrollOffsetReaderUIViewController(im)viewDidAppear:","modules":[{"name":"CleanUI"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}]},"hierarchy":{"paths":[["doc:\/\/CleanUI\/documentation\/CleanUI","doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController"]]},"references":{"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller\/viewdidappear(_:)"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController":{"role":"symbol","title":"CUScrollOffsetReaderUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller"},"doc://CleanUI/documentation/CleanUI":{"role":"collection","title":"CleanUI","abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI","kind":"symbol","type":"topic","url":"\/documentation\/cleanui"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidAppear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/title","value":"CUScrollOffsetReaderUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/fragments","value":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}