{"variants":[{"paths":["\/documentation\/cleanui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cleanui"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/CleanUI\/documentation\/CleanUI","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlert","doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessage","doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessages","doc:\/\/CleanUI\/documentation\/CleanUI\/CUBrowser","doc:\/\/CleanUI\/documentation\/CleanUI\/CUInAppNotification","doc:\/\/CleanUI\/documentation\/CleanUI\/CULanguage","doc:\/\/CleanUI\/documentation\/CleanUI\/CUNavigation","doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController","doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewControllerRepresentable","doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet","doc:\/\/CleanUI\/documentation\/CleanUI\/CUStd","doc:\/\/CleanUI\/documentation\/CleanUI\/CUTime","doc:\/\/CleanUI\/documentation\/CleanUI\/InfoCardManagerModel"]},{"title":"Structures","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CLAlertConfirmView","doc:\/\/CleanUI\/documentation\/CleanUI\/CLBlurView","doc:\/\/CleanUI\/documentation\/CleanUI\/CLCard","doc:\/\/CleanUI\/documentation\/CleanUI\/CLCircularProgress","doc:\/\/CleanUI\/documentation\/CleanUI\/CLDateTime","doc:\/\/CleanUI\/documentation\/CleanUI\/CLDescriptiveNumber","doc:\/\/CleanUI\/documentation\/CleanUI\/CLExpandableText","doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedFooter","doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedTitle","doc:\/\/CleanUI\/documentation\/CleanUI\/CLIcon","doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCard","doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCardManager","doc:\/\/CleanUI\/documentation\/CleanUI\/CLKnogglGradient","doc:\/\/CleanUI\/documentation\/CleanUI\/CLLinearProgress","doc:\/\/CleanUI\/documentation\/CleanUI\/CLLoadingIndicator","doc:\/\/CleanUI\/documentation\/CleanUI\/CLNavigationView","doc:\/\/CleanUI\/documentation\/CleanUI\/CLNewBadge","doc:\/\/CleanUI\/documentation\/CleanUI\/CLRichText","doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollOffsetReader","doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollView","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSearchBar","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetConfirmView","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetMenu","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetMenuItem","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetTitle","doc:\/\/CleanUI\/documentation\/CleanUI\/CLSingleLineTextEditor","doc:\/\/CleanUI\/documentation\/CleanUI\/CLText","doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextEditor","doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldLabel","doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldProgress","doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextWithNewBadge","doc:\/\/CleanUI\/documentation\/CleanUI\/CLUrlImage","doc:\/\/CleanUI\/documentation\/CleanUI\/CLWebview","doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertModel","doc:\/\/CleanUI\/documentation\/CleanUI\/CUGlobal","doc:\/\/CleanUI\/documentation\/CleanUI\/ChatTextFieldStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/CleanUI","doc:\/\/CleanUI\/documentation\/CleanUI\/HideNavigationBar","doc:\/\/CleanUI\/documentation\/CleanUI\/IconRoundOverImageButtonStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/ImageOverlayButtonStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/MenuButtonStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/NavigationBar","doc:\/\/CleanUI\/documentation\/CleanUI\/OnLoad","doc:\/\/CleanUI\/documentation\/CleanUI\/OnRotate","doc:\/\/CleanUI\/documentation\/CleanUI\/PinchToZoom","doc:\/\/CleanUI\/documentation\/CleanUI\/PreviewContextMenu","doc:\/\/CleanUI\/documentation\/CleanUI\/PreviewContextMenuOverlay","doc:\/\/CleanUI\/documentation\/CleanUI\/PrimaryButtonStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/PrimaryTextFieldStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/RoundedButtonStyle","doc:\/\/CleanUI\/documentation\/CleanUI\/RoundedCorner","doc:\/\/CleanUI\/documentation\/CleanUI\/SecondaryButtonStyle"]},{"title":"Type Aliases","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/PlatformView"]},{"title":"Enumerations","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/Attribute","doc:\/\/CleanUI\/documentation\/CleanUI\/CUVibrate"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"CleanUI","title":"CleanUI","symbolKind":"module","role":"collection","modules":[{"name":"CleanUI"}]},"hierarchy":{"paths":[[]]},"references":{"doc://CleanUI/documentation/CleanUI/NavigationBar":{"role":"symbol","title":"NavigationBar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBar"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/NavigationBar"},{"type":"text","text":" modifier applies a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/NavigationBar"},{"type":"text","text":" to the view and removes the default UINavigationBar."},{"type":"text","text":" "},{"type":"text","text":"Use only on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLNavigationView"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/NavigationBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationBar"}],"url":"\/documentation\/cleanui\/navigationbar"},"doc://CleanUI/documentation/CleanUI/CLWebview":{"role":"symbol","title":"CLWebview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLWebview"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLWebview"},{"type":"text","text":" is a UIViewRepresentable for an `WKWebView"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLWebview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLWebview"}],"url":"\/documentation\/cleanui\/clwebview"},"doc://CleanUI/documentation/CleanUI/CUTime":{"role":"symbol","title":"CUTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUTime"}],"abstract":[{"type":"text","text":"This is a time \/ Date helper class"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUTime"}],"url":"\/documentation\/cleanui\/cutime"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController":{"role":"symbol","title":"CUScrollOffsetReaderUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller"},"doc://CleanUI/documentation/CleanUI/HideNavigationBar":{"role":"symbol","title":"HideNavigationBar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HideNavigationBar"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/HideNavigationBar"},{"type":"text","text":" modifier hides the default UINavigationBar"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/HideNavigationBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HideNavigationBar"}],"url":"\/documentation\/cleanui\/hidenavigationbar"},"doc://CleanUI/documentation/CleanUI/OnRotate":{"role":"symbol","title":"OnRotate","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnRotate"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/OnRotate"},{"type":"text","text":" modifier gives you the ability to react to device rotations"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/OnRotate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnRotate"}],"url":"\/documentation\/cleanui\/onrotate"},"doc://CleanUI/documentation/CleanUI/InfoCardManagerModel":{"role":"symbol","title":"InfoCardManagerModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoCardManagerModel"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/InfoCardManagerModel"},{"type":"text","text":" manages the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCardManager"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/InfoCardManagerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoCardManagerModel"}],"url":"\/documentation\/cleanui\/infocardmanagermodel"},"doc://CleanUI/documentation/CleanUI/CLFeedFooter":{"role":"symbol","title":"CLFeedFooter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLFeedFooter"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedFooter"},{"type":"text","text":" for implementation in feeds or forms"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedFooter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLFeedFooter"}],"url":"\/documentation\/cleanui\/clfeedfooter"},"doc://CleanUI/documentation/CleanUI/CUBrowser":{"role":"symbol","title":"CUBrowser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUBrowser"}],"abstract":[{"type":"text","text":"This class handles browser windows"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUBrowser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUBrowser"}],"url":"\/documentation\/cleanui\/cubrowser"},"doc://CleanUI/documentation/CleanUI/CLDateTime":{"role":"symbol","title":"CLDateTime","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLDateTime"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLDateTime"},{"type":"text","text":" is an expandable date and time object which updates automatically"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLDateTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLDateTime"}],"url":"\/documentation\/cleanui\/cldatetime"},"doc://CleanUI/documentation/CleanUI/CUNavigation":{"role":"symbol","title":"CUNavigation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUNavigation"}],"abstract":[{"type":"text","text":"This class handles all sorts of programmatic navigation"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUNavigation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUNavigation"}],"url":"\/documentation\/cleanui\/cunavigation"},"doc://CleanUI/documentation/CleanUI/ImageOverlayButtonStyle":{"role":"symbol","title":"ImageOverlayButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageOverlayButtonStyle"}],"abstract":[{"type":"text","text":"ImageOverlayButtonStyle: ButtonStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/ImageOverlayButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageOverlayButtonStyle"}],"url":"\/documentation\/cleanui\/imageoverlaybuttonstyle"},"doc://CleanUI/documentation/CleanUI/OnLoad":{"role":"symbol","title":"OnLoad","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnLoad"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/OnLoad"},{"type":"text","text":" ViewModifier allows to add a "},{"type":"codeVoice","code":".onLoad { action() }"},{"type":"text","text":" to a view,"},{"type":"text","text":" "},{"type":"text","text":"The action() never gets called twice"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/OnLoad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnLoad"}],"url":"\/documentation\/cleanui\/onload"},"doc://CleanUI/documentation/CleanUI":{"role":"collection","title":"CleanUI","abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI","kind":"symbol","type":"topic","url":"\/documentation\/cleanui"},"doc://CleanUI/documentation/CleanUI/CLLinearProgress":{"role":"symbol","title":"CLLinearProgress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLLinearProgress"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLLinearProgress"},{"type":"text","text":"  for indacting any type of progress"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLLinearProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLLinearProgress"}],"url":"\/documentation\/cleanui\/cllinearprogress"},"doc://CleanUI/documentation/CleanUI/CLIcon":{"role":"symbol","title":"CLIcon","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLIcon"}],"abstract":[{"type":"text","text":"Returns a very dynamic and customizable "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLIcon"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLIcon"}],"url":"\/documentation\/cleanui\/clicon"},"doc://CleanUI/documentation/CleanUI/CLRichText":{"role":"symbol","title":"CLRichText","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLRichText"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLRichText"},{"type":"text","text":" with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/Attribute"},{"type":"text","text":" highlighting and onTap actions"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLRichText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLRichText"}],"url":"\/documentation\/cleanui\/clrichtext"},"doc://CleanUI/documentation/CleanUI/CLAlertConfirmView":{"role":"symbol","title":"CLAlertConfirmView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLAlertConfirmView"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLAlertConfirmView"},{"type":"text","text":" is a action confirmation view for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlert"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLAlertConfirmView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLAlertConfirmView"}],"url":"\/documentation\/cleanui\/clalertconfirmview"},"doc://CleanUI/documentation/CleanUI/CUInAppNotification":{"role":"symbol","title":"CUInAppNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUInAppNotification"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUInAppNotification"},{"type":"text","text":" allows to show and hide in app notifications"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUInAppNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUInAppNotification"}],"url":"\/documentation\/cleanui\/cuinappnotification"},"doc://CleanUI/documentation/CleanUI/CLTextEditor":{"role":"symbol","title":"CLTextEditor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLTextEditor"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextEditor"},{"type":"text","text":" with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/Attribute"},{"type":"text","text":" highlighting, character limit, and placeholder"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextEditor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLTextEditor"}],"url":"\/documentation\/cleanui\/cltexteditor"},"doc://CleanUI/documentation/CleanUI/CLKnogglGradient":{"role":"symbol","title":"CLKnogglGradient","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLKnogglGradient"}],"abstract":[{"type":"text","text":"Returns the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLKnogglGradient"},{"type":"text","text":" a "},{"type":"codeVoice","code":"LinearGradient"},{"type":"text","text":" in Knoggl style"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLKnogglGradient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLKnogglGradient"}],"url":"\/documentation\/cleanui\/clknogglgradient"},"doc://CleanUI/documentation/CleanUI/IconRoundOverImageButtonStyle":{"role":"symbol","title":"IconRoundOverImageButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IconRoundOverImageButtonStyle"}],"abstract":[{"type":"text","text":"IconRoundOverImageButtonStyle: ButtonStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/IconRoundOverImageButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IconRoundOverImageButtonStyle"}],"url":"\/documentation\/cleanui\/iconroundoverimagebuttonstyle"},"doc://CleanUI/documentation/CleanUI/ChatTextFieldStyle":{"role":"symbol","title":"ChatTextFieldStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatTextFieldStyle"}],"abstract":[{"type":"text","text":"ChatTextFieldStyle: TextFieldStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/ChatTextFieldStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatTextFieldStyle"}],"url":"\/documentation\/cleanui\/chattextfieldstyle"},"doc://CleanUI/documentation/CleanUI/CLSearchBar":{"role":"symbol","title":"CLSearchBar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSearchBar"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSearchBar"},{"type":"text","text":" is a "},{"type":"codeVoice","code":"UIViewRepresentable"},{"type":"text","text":" for an "},{"type":"codeVoice","code":"UISearchBar"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSearchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSearchBar"}],"url":"\/documentation\/cleanui\/clsearchbar"},"doc://CleanUI/documentation/CleanUI/CLLoadingIndicator":{"role":"symbol","title":"CLLoadingIndicator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLLoadingIndicator"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLLoadingIndicator"},{"type":"text","text":" for indicating unknown progress"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLLoadingIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLLoadingIndicator"}],"url":"\/documentation\/cleanui\/clloadingindicator"},"doc://CleanUI/documentation/CleanUI/CleanUI":{"role":"symbol","title":"CleanUI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CleanUI"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CleanUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CleanUI"}],"url":"\/documentation\/cleanui\/cleanui"},"doc://CleanUI/documentation/CleanUI/RoundedCorner":{"role":"symbol","title":"RoundedCorner","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedCorner"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"codeVoice","code":"Shape"},{"type":"text","text":" with custom corner radius"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/RoundedCorner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoundedCorner"}],"url":"\/documentation\/cleanui\/roundedcorner"},"doc://CleanUI/documentation/CleanUI/CULanguage":{"role":"symbol","title":"CULanguage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CULanguage"}],"abstract":[{"type":"text","text":"This class helps to get translations"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CULanguage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CULanguage"}],"url":"\/documentation\/cleanui\/culanguage"},"doc://CleanUI/documentation/CleanUI/CLSheetConfirmView":{"role":"symbol","title":"CLSheetConfirmView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSheetConfirmView"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetConfirmView"},{"type":"text","text":" is a action confirmation view for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetConfirmView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSheetConfirmView"}],"url":"\/documentation\/cleanui\/clsheetconfirmview"},"doc://CleanUI/documentation/CleanUI/CLSheetMenu":{"role":"symbol","title":"CLSheetMenu","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSheetMenu"}],"abstract":[{"type":"text","text":"Returns a styled menu for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSheetMenu"}],"url":"\/documentation\/cleanui\/clsheetmenu"},"doc://CleanUI/documentation/CleanUI/CLSheetMenuItem":{"role":"symbol","title":"CLSheetMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSheetMenuItem"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSheetMenuItem"}],"url":"\/documentation\/cleanui\/clsheetmenuitem"},"doc://CleanUI/documentation/CleanUI/CUAlertModel":{"role":"symbol","title":"CUAlertModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUAlertModel"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertModel"},{"type":"text","text":" is used for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlert"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUInAppNotification"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessage"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUAlertModel"}],"url":"\/documentation\/cleanui\/cualertmodel"},"doc://CleanUI/documentation/CleanUI/CLFeedTitle":{"role":"symbol","title":"CLFeedTitle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLFeedTitle"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedTitle"},{"type":"text","text":" for implementation in feeds or forms"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLFeedTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLFeedTitle"}],"url":"\/documentation\/cleanui\/clfeedtitle"},"doc://CleanUI/documentation/CleanUI/CLNewBadge":{"role":"symbol","title":"CLNewBadge","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLNewBadge"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLNewBadge"},{"type":"text","text":" for indicating that something is unseen or new"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLNewBadge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLNewBadge"}],"url":"\/documentation\/cleanui\/clnewbadge"},"doc://CleanUI/documentation/CleanUI/SecondaryButtonStyle":{"role":"symbol","title":"SecondaryButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButtonStyle"}],"abstract":[{"type":"text","text":"SecondaryButtonStyle: ButtonStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/SecondaryButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecondaryButtonStyle"}],"url":"\/documentation\/cleanui\/secondarybuttonstyle"},"doc://CleanUI/documentation/CleanUI/CLInfoCardManager":{"role":"symbol","title":"CLInfoCardManager","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLInfoCardManager"}],"abstract":[{"type":"text","text":"Returns a view which is able to decide if and which "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCard"},{"type":"text","text":" should be displayed based on a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/InfoCardManagerModel"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCardManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLInfoCardManager"}],"url":"\/documentation\/cleanui\/clinfocardmanager"},"doc://CleanUI/documentation/CleanUI/CLNavigationView":{"role":"symbol","title":"CLNavigationView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLNavigationView"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLNavigationView"},{"type":"text","text":" is a wrapper for NavigationView."}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLNavigationView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLNavigationView"}],"url":"\/documentation\/cleanui\/clnavigationview"},"doc://CleanUI/documentation/CleanUI/CLSingleLineTextEditor":{"role":"symbol","title":"CLSingleLineTextEditor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSingleLineTextEditor"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSingleLineTextEditor"},{"type":"text","text":". The editor is first single line and expands on line break"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSingleLineTextEditor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSingleLineTextEditor"}],"url":"\/documentation\/cleanui\/clsinglelinetexteditor"},"doc://CleanUI/documentation/CleanUI/CLExpandableText":{"role":"symbol","title":"CLExpandableText","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLExpandableText"}],"abstract":[{"type":"text","text":"Returns an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLExpandableText"},{"type":"text","text":" which has a show more \/ show less button if the"},{"type":"text","text":" "},{"type":"text","text":"provided string is longer than the "},{"type":"codeVoice","code":"characterLimit"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLExpandableText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLExpandableText"}],"url":"\/documentation\/cleanui\/clexpandabletext"},"doc://CleanUI/documentation/CleanUI/PinchToZoom":{"role":"symbol","title":"PinchToZoom","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PinchToZoom"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PinchToZoom"},{"type":"text","text":" modifier adds a pinch to zoom ability to a View"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PinchToZoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PinchToZoom"}],"url":"\/documentation\/cleanui\/pinchtozoom"},"doc://CleanUI/documentation/CleanUI/CLTextFieldLabel":{"role":"symbol","title":"CLTextFieldLabel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLTextFieldLabel"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldLabel"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLTextFieldLabel"}],"url":"\/documentation\/cleanui\/cltextfieldlabel"},"doc://CleanUI/documentation/CleanUI/CUStd":{"role":"symbol","title":"CUStd","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUStd"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CUStd"},{"type":"text","text":" class provides a collection of static standard functions"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUStd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUStd"}],"url":"\/documentation\/cleanui\/custd"},"doc://CleanUI/documentation/CleanUI/Attribute":{"role":"symbol","title":"Attribute","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attribute"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/Attribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Attribute"}],"url":"\/documentation\/cleanui\/attribute"},"doc://CleanUI/documentation/CleanUI/CLText":{"role":"symbol","title":"CLText","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLText"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLText"}],"url":"\/documentation\/cleanui\/cltext"},"doc://CleanUI/documentation/CleanUI/PrimaryTextFieldStyle":{"role":"symbol","title":"PrimaryTextFieldStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrimaryTextFieldStyle"}],"abstract":[{"type":"text","text":"PrimaryTextFieldStyle: TextFieldStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PrimaryTextFieldStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrimaryTextFieldStyle"}],"url":"\/documentation\/cleanui\/primarytextfieldstyle"},"doc://CleanUI/documentation/CleanUI/PlatformView":{"role":"symbol","title":"PlatformView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformView"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PlatformView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformView"}],"url":"\/documentation\/cleanui\/platformview"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewControllerRepresentable":{"role":"symbol","title":"CUScrollOffsetReaderUIViewControllerRepresentable","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewControllerRepresentable"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewControllerRepresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewControllerRepresentable"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontrollerrepresentable"},"doc://CleanUI/documentation/CleanUI/CUAlert":{"role":"symbol","title":"CUAlert","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUAlert"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlert"},{"type":"text","text":" allows to show and hide Alerts"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUAlert"}],"url":"\/documentation\/cleanui\/cualert"},"doc://CleanUI/documentation/CleanUI/CUGlobal":{"role":"symbol","title":"CUGlobal","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUGlobal"}],"abstract":[{"type":"text","text":"Global static variables are stored here"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUGlobal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUGlobal"}],"url":"\/documentation\/cleanui\/cuglobal"},"doc://CleanUI/documentation/CleanUI/CLCircularProgress":{"role":"symbol","title":"CLCircularProgress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLCircularProgress"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLCircularProgress"},{"type":"text","text":" for indacting any type of progress"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLCircularProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLCircularProgress"}],"url":"\/documentation\/cleanui\/clcircularprogress"},"doc://CleanUI/documentation/CleanUI/CUAlertMessage":{"role":"symbol","title":"CUAlertMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUAlertMessage"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessage"},{"type":"text","text":" is able to show a toast like message at the bottom of the"},{"type":"text","text":" "},{"type":"text","text":"screen. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessage"},{"type":"text","text":" uses "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCard"},{"type":"text","text":"’s."}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUAlertMessage"}],"url":"\/documentation\/cleanui\/cualertmessage"},"doc://CleanUI/documentation/CleanUI/CLBlurView":{"role":"symbol","title":"CLBlurView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLBlurView"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLBlurView"},{"type":"text","text":" is a UIViewRepresentable for an "},{"type":"codeVoice","code":"UIVisualEffectView"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLBlurView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLBlurView"}],"url":"\/documentation\/cleanui\/clblurview"},"doc://CleanUI/documentation/CleanUI/PreviewContextMenu":{"role":"symbol","title":"PreviewContextMenu","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewContextMenu"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PreviewContextMenu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewContextMenu"}],"url":"\/documentation\/cleanui\/previewcontextmenu"},"doc://CleanUI/documentation/CleanUI/CUAlertMessages":{"role":"symbol","title":"CUAlertMessages","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUAlertMessages"}],"abstract":[{"type":"text","text":"This class handles all alert messages"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUAlertMessages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUAlertMessages"}],"url":"\/documentation\/cleanui\/cualertmessages"},"doc://CleanUI/documentation/CleanUI/CUVibrate":{"role":"symbol","title":"CUVibrate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUVibrate"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUVibrate"},{"type":"text","text":" helps you to play vibrations"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUVibrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUVibrate"}],"url":"\/documentation\/cleanui\/cuvibrate"},"doc://CleanUI/documentation/CleanUI/CLScrollOffsetReader":{"role":"symbol","title":"CLScrollOffsetReader","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLScrollOffsetReader"}],"abstract":[{"type":"text","text":"This "},{"type":"codeVoice","code":"View"},{"type":"text","text":" is able to find the first "},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" "},{"type":"text","text":"in the "},{"type":"codeVoice","code":"Content"},{"type":"text","text":" view hierarchy. If a "},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" is found, it returns a scroll offset, else nil"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollOffsetReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLScrollOffsetReader"}],"url":"\/documentation\/cleanui\/clscrolloffsetreader"},"doc://CleanUI/documentation/CleanUI/CLTextWithNewBadge":{"role":"symbol","title":"CLTextWithNewBadge","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLTextWithNewBadge"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextWithNewBadge"},{"type":"text","text":" (Text with optional ``CLNewBadge`)"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextWithNewBadge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLTextWithNewBadge"}],"url":"\/documentation\/cleanui\/cltextwithnewbadge"},"doc://CleanUI/documentation/CleanUI/CLTextFieldProgress":{"role":"symbol","title":"CLTextFieldProgress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLTextFieldProgress"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldProgress"},{"type":"text","text":" view for indication how much the user is allowed to type inside a TextField or TextEditor"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLTextFieldProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLTextFieldProgress"}],"url":"\/documentation\/cleanui\/cltextfieldprogress"},"doc://CleanUI/documentation/CleanUI/CLDescriptiveNumber":{"role":"symbol","title":"CLDescriptiveNumber","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLDescriptiveNumber"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLDescriptiveNumber"},{"type":"text","text":" with a number and an description, aligned vertically"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLDescriptiveNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLDescriptiveNumber"}],"url":"\/documentation\/cleanui\/cldescriptivenumber"},"doc://CleanUI/documentation/CleanUI/CLUrlImage":{"role":"symbol","title":"CLUrlImage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLUrlImage"}],"abstract":[{"type":"text","text":"Returns an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLUrlImage"},{"type":"text","text":" which fetches a image from an url, displays and caches it, if needed"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLUrlImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLUrlImage"}],"url":"\/documentation\/cleanui\/clurlimage"},"doc://CleanUI/documentation/CleanUI/PrimaryButtonStyle":{"role":"symbol","title":"PrimaryButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrimaryButtonStyle"}],"abstract":[{"type":"text","text":"PrimaryButtonStyle: ButtonStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PrimaryButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrimaryButtonStyle"}],"url":"\/documentation\/cleanui\/primarybuttonstyle"},"doc://CleanUI/documentation/CleanUI/CLScrollView":{"role":"symbol","title":"CLScrollView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLScrollView"}],"abstract":[{"type":"text","text":"This is a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollView"},{"type":"text","text":" which is mainly an SwiftUI.ScrollView. In contrast to SwiftUI.CLScrollView, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollView"},{"type":"text","text":" "},{"type":"text","text":"is able to return the scroll offset"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLScrollView"}],"url":"\/documentation\/cleanui\/clscrollview"},"doc://CleanUI/documentation/CleanUI/CLInfoCard":{"role":"symbol","title":"CLInfoCard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLInfoCard"}],"abstract":[{"type":"text","text":"Returns a view, in style of a card with text for information. If there is the possibility that multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCard"},{"type":"text","text":"’s"},{"type":"text","text":" "},{"type":"text","text":"gets shown, consider using a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCardManager"},{"type":"text","text":" instead."}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLInfoCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLInfoCard"}],"url":"\/documentation\/cleanui\/clinfocard"},"doc://CleanUI/documentation/CleanUI/MenuButtonStyle":{"role":"symbol","title":"MenuButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuButtonStyle"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/MenuButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenuButtonStyle"}],"url":"\/documentation\/cleanui\/menubuttonstyle"},"doc://CleanUI/documentation/CleanUI/PreviewContextMenuOverlay":{"role":"symbol","title":"PreviewContextMenuOverlay","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewContextMenuOverlay"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/PreviewContextMenuOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewContextMenuOverlay"}],"url":"\/documentation\/cleanui\/previewcontextmenuoverlay"},"doc://CleanUI/documentation/CleanUI/CLSheetTitle":{"role":"symbol","title":"CLSheetTitle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLSheetTitle"}],"abstract":[{"type":"text","text":"Returns a title view for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLSheetTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLSheetTitle"}],"url":"\/documentation\/cleanui\/clsheettitle"},"doc://CleanUI/documentation/CleanUI/CUSheet":{"role":"symbol","title":"CUSheet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUSheet"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet"},{"type":"text","text":" allows to show and hide Sheets"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUSheet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUSheet"}],"url":"\/documentation\/cleanui\/cusheet"},"doc://CleanUI/documentation/CleanUI/RoundedButtonStyle":{"role":"symbol","title":"RoundedButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedButtonStyle"}],"abstract":[{"type":"text","text":"RoundedButtonStyle: ButtonStyle"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/RoundedButtonStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoundedButtonStyle"}],"url":"\/documentation\/cleanui\/roundedbuttonstyle"},"doc://CleanUI/documentation/CleanUI/CLCard":{"role":"symbol","title":"CLCard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLCard"}],"abstract":[{"type":"text","text":"Adds a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLCard"},{"type":"text","text":" style to a view without wrapping it inside a container"}],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CLCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLCard"}],"url":"\/documentation\/cleanui\/clcard"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController"]}]},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/title","value":"CUScrollOffsetReaderUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/fragments","value":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}