{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/CleanUI\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/CleanUI\/objc(pl)NSCoding","doc:\/\/CleanUI\/objc(pl)NSExtensionRequestHandling","doc:\/\/CleanUI\/objc(pl)NSObject","doc:\/\/CleanUI\/s7CVarArgP","doc:\/\/CleanUI\/s28CustomDebugStringConvertibleP","doc:\/\/CleanUI\/s23CustomStringConvertibleP","doc:\/\/CleanUI\/SQ","doc:\/\/CleanUI\/SH","doc:\/\/CleanUI\/s8SendableP","doc:\/\/CleanUI\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/CleanUI\/objc(pl)UIAppearanceContainer","doc:\/\/CleanUI\/objc(pl)UIContentContainer","doc:\/\/CleanUI\/objc(pl)UIFocusEnvironment","doc:\/\/CleanUI\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/CleanUI\/objc(pl)UIResponderStandardEditActions","doc:\/\/CleanUI\/objc(pl)UIStateRestoring","doc:\/\/CleanUI\/objc(pl)UITraitEnvironment","doc:\/\/CleanUI\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/init(offsetChanged:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/viewDidAppear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"title":"CUScrollOffsetReaderUIViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CleanUI@objc(cs)CUScrollOffsetReaderUIViewController","modules":[{"name":"CleanUI"}],"navigatorTitle":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]},"hierarchy":{"paths":[["doc:\/\/CleanUI\/documentation\/CleanUI"]]},"references":{"doc://CleanUI/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/CleanUI\/s8SendableP"},"doc://CleanUI/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/CleanUI\/objc(pl)NSCoding"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController/init(offsetChanged:)":{"role":"symbol","title":"init(offsetChanged:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offsetChanged"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/init(offsetChanged:)","kind":"symbol","type":"topic","url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller\/init(offsetchanged:)"},"doc://CleanUI/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/CleanUI\/objc(pl)UITraitEnvironment"},"doc://CleanUI/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/CleanUI\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://CleanUI/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/CleanUI\/objc(cs)UIViewController"},"doc://CleanUI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/CleanUI\/s23CustomStringConvertibleP"},"doc://CleanUI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/CleanUI\/SH"},"doc://CleanUI/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/CleanUI\/objc(pl)UIAppearanceContainer"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller\/viewdidappear(_:)"},"doc://CleanUI/documentation/CleanUI":{"role":"collection","title":"CleanUI","abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI","kind":"symbol","type":"topic","url":"\/documentation\/cleanui"},"doc://CleanUI/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/CleanUI\/objc(pl)NSExtensionRequestHandling"},"doc://CleanUI/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/CleanUI\/objc(pl)UIContentContainer"},"doc://CleanUI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/CleanUI\/SQ"},"doc://CleanUI/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/CleanUI\/objc(pl)UIStateRestoring"},"doc://CleanUI/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/CleanUI\/objc(pl)UIResponderStandardEditActions"},"doc://CleanUI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/CleanUI\/s7CVarArgP"},"doc://CleanUI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/CleanUI\/s28CustomDebugStringConvertibleP"},"doc://CleanUI/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/CleanUI\/objc(pl)UIPasteConfigurationSupporting"},"doc://CleanUI/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/CleanUI\/objc(pl)UIFocusEnvironment"},"doc://CleanUI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/CleanUI\/objc(pl)NSObject"},"doc://CleanUI/documentation/CleanUI/CUScrollOffsetReaderUIViewController":{"role":"symbol","title":"CUScrollOffsetReaderUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"abstract":[],"identifier":"doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}],"url":"\/documentation\/cleanui\/cuscrolloffsetreaderuiviewcontroller"},"doc://CleanUI/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/CleanUI\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CUScrollOffsetReaderUIViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/CleanUI\/documentation\/CleanUI\/CUScrollOffsetReaderUIViewController\/viewDidAppear(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/title","value":"CUScrollOffsetReaderUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1CleanUI~1documentation~1CleanUI~1CUScrollOffsetReaderUIViewController\/fragments","value":[{"kind":"identifier","text":"CUScrollOffsetReaderUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}